// 16x16 pixel icons for the achievement toasts. Same format as Lua's sprites: one palette key
// per pixel, "." is transparent. A few reuse Lua herself.

import { PALETTE, SLEEP, type Sprite } from "../lua/sprites";

const P: Record<string, string> = {
  K: "#0d0d0c", // outline
  W: "#e9e7e1",
  w: "#8b8881",
  d: "#4a4f57",
  G: "#8ae234",
  g: "#4e9a06",
  Y: "#f2c94c",
  y: "#b8860b",
  B: "#7fb7e6",
  b: "#3d6e9e",
  R: "#ef4444",
  A: "#e8a33a",
  O: "#c8a26b",
  P: "#e79a9a",
  C: "#5fd7d7",
  N: "#6b4226",
};

export type Icon = { sprite: Sprite; palette: Record<string, string> };

const icon = (sprite: Sprite): Icon => ({ sprite, palette: P });

export const ICONS: Record<string, Icon> = {
  // an open book
  curious: icon([
    "................",
    "................",
    "..KKKKK..KKKKK..",
    ".KWWWWWKKWWWWWK.",
    ".KWwwwWKKWwwwWK.",
    ".KWWWWWKKWWWWWK.",
    ".KWwwwWKKWwwwWK.",
    ".KWWWWWKKWWWWWK.",
    ".KWwwwWKKWwwwWK.",
    ".KWWWWWKKWWWWWK.",
    ".KWWWWWKKWWWWWK.",
    ".KKKKKKBBKKKKKK.",
    "..bbbbbBBbbbbb..",
    "................",
    "................",
    "................",
  ]),
  // a green warp pipe
  pipe: icon([
    "................",
    "..KKKKKKKKKKKK..",
    "..KGGGGGGGGgGK..",
    "..KGWGGGGGGgGK..",
    "..KGGGGGGGGgGK..",
    "..KKKKKKKKKKKK..",
    "...KGWGGGGgGK...",
    "...KGWGGGGgGK...",
    "...KGWGGGGgGK...",
    "...KGWGGGGgGK...",
    "...KGWGGGGgGK...",
    "...KGWGGGGgGK...",
    "...KGWGGGGgGK...",
    "...KGWGGGGgGK...",
    "...KKKKKKKKKK...",
    "................",
  ]),
  // a clock
  search: icon([
    "................",
    ".....KKKKKK.....",
    "...KKWWWWWWKK...",
    "..KWWWWKWWWWWK..",
    "..KWWWWKWWWWWK..",
    ".KWWWWWKWWWWWWK.",
    ".KWWWWWKWWWWWWK.",
    ".KWWWWWKKKKWWWK.",
    ".KWWWWWWWWWWWWK.",
    ".KWWWWWWWWWWWWK.",
    "..KWWWWWWWWWWK..",
    "..KWWWWWWWWWWK..",
    "...KKWWWWWWKK...",
    ".....KKKKKK.....",
    "................",
    "................",
  ]),
  // vim's green diamond
  vim: icon([
    ".......KK.......",
    "......KGGK......",
    ".....KGGGGK.....",
    "....KGGGGGGK....",
    "...KWWGGGGWWK...",
    "..KGWWGGGGWWGK..",
    ".KGGGWWGGWWGGGK.",
    "KGGGGWWGGWWGGGGK",
    ".KGGGGWWWWGGGGK.",
    "..KGGGGWWGGGGK..",
    "...KGGGWWGGGK...",
    "....KGGGGGGK....",
    ".....KGGGGK.....",
    "......KGGK......",
    ".......KK.......",
    "................",
  ]),
  // a paint palette
  theme: icon([
    "................",
    "....KKKKKKK.....",
    "..KKOOOOOOOKK...",
    ".KOORROOOBBOOK..",
    ".KOORROOOBBOOK..",
    "KOOOOOOOOOOOOOK.",
    "KOGGOOOOOOOOOOK.",
    "KOGGOOOKKKOOOOK.",
    "KOOOOOK...KOOOK.",
    "KOOYYOK...KOOK..",
    ".KOYYOOKKKOOK...",
    ".KOOOOOOOOOK....",
    "..KKOOOOOKK.....",
    "....KKKKK.......",
    "................",
    "................",
  ]),
  // a heart
  pets: icon([
    "................",
    "................",
    "...KKK...KKK....",
    "..KRRRK.KRRRK...",
    ".KRWRRRKRRRRRK..",
    ".KRWRRRRRRRRRK..",
    ".KRRRRRRRRRRRK..",
    ".KRRRRRRRRRRRK..",
    "..KRRRRRRRRRK...",
    "...KRRRRRRRK....",
    "....KRRRRRK.....",
    ".....KRRRK......",
    "......KRK.......",
    ".......K........",
    "................",
    "................",
  ]),
  // a paw print
  follow: icon([
    "................",
    "....KKK..KKK....",
    "...KPPPKKPPPK...",
    "...KPPPKKPPPK...",
    "KKK.KKK..KKK.KKK",
    "KPPK........KPPK",
    "KPPK.KKKKKK.KPPK",
    ".KK.KPPPPPPK.KK.",
    "...KPPPPPPPPK...",
    "..KPPPPPPPPPPK..",
    "..KPPPPPPPPPPK..",
    "..KPPPPPPPPPPK..",
    "...KPPPPPPPPK...",
    "....KKKKKKKK....",
    "................",
    "................",
  ]),
  // a padlock
  sudo: icon([
    "................",
    ".....KKKKKK.....",
    "....KwwwwwwK....",
    "...KwKKKKKKwK...",
    "...KwK....KwK...",
    "...KwK....KwK...",
    "..KKKKKKKKKKKK..",
    "..KYYYYYYYYYyK..",
    "..KYWYKKKYYYyK..",
    "..KYYYKKKYYYyK..",
    "..KYYYYKYYYYyK..",
    "..KYYYYKYYYYyK..",
    "..KYYYYYYYYYyK..",
    "..KyyyyyyyyyyK..",
    "..KKKKKKKKKKKK..",
    "................",
  ]),
  // fire
  rm: icon([
    "................",
    ".......K........",
    "......KRK.......",
    "......KRRK......",
    ".....KRRRK..K...",
    "....KRRARRK.KK..",
    "...KRRRAARRKRK..",
    "...KRRAAAARRRK..",
    "..KRRAAYYAARRK..",
    "..KRAAYYYYAARK..",
    "..KRAYYWWYYARK..",
    "..KRAYWWWWYARK..",
    "...KRAYWWYARK...",
    "....KKRRRRKK....",
    "......KKKK......",
    "................",
  ]),
  // lua asleep
  afk: { sprite: SLEEP, palette: PALETTE },
  // a page of notes
  reader: icon([
    "................",
    "...KKKKKKKKK....",
    "...KWWWWWWWKK...",
    "...KWwwwwWWKWK..",
    "...KWWWWWWWKKKK.",
    "...KWwwwwwwWWWK.",
    "...KWWWWWWWWWWK.",
    "...KWwwwwwwwwWK.",
    "...KWWWWWWWWWWK.",
    "...KWwwwwwwwWWK.",
    "...KWWWWWWWWWWK.",
    "...KWwwwwwwwwWK.",
    "...KWWWWWWWWWWK.",
    "...KKKKKKKKKKKK.",
    "................",
    "................",
  ]),
  // a steaming mug
  teapot: icon([
    "................",
    "....w...w.......",
    ".....w...w......",
    "....w...w.......",
    "................",
    "..KKKKKKKKKK....",
    "..KNNNNNNNNKKK..",
    "..KWWWWWWWWK.KK.",
    "..KWWWWWWWWK..K.",
    "..KWWWWWWWWK..K.",
    "..KWWWWWWWWK.KK.",
    "..KWWWWWWWWKKK..",
    "..KWWWWWWWWK....",
    "...KWWWWWWK.....",
    "....KKKKKK......",
    "................",
  ]),
  // a ? block
  lost: icon([
    "KKKKKKKKKKKKKKKK",
    "KYYYYYYYYYYYYYyK",
    "KYKYYYYYYYYYKYyK",
    "KYYYYKKKKKYYYYyK",
    "KYYYKKyyyKKYYYyK",
    "KYYYKKyYYKKyYYyK",
    "KYYYYyyYYKKyYYyK",
    "KYYYYYYYKKyyYYyK",
    "KYYYYYYKKyyYYYyK",
    "KYYYYYYKKyYYYYyK",
    "KYYYYYYYyyYYYYyK",
    "KYYYYYYKKYYYYYyK",
    "KYYYYYYKKyYYYYyK",
    "KYKYYYYYyyYYKYyK",
    "KyyyyyyyyyyyyyyK",
    "KKKKKKKKKKKKKKKK",
  ]),
  // a flag
  run: icon([
    "................",
    "..KK............",
    "..KwKKKKKKK.....",
    "..KwKGGGGGGKK...",
    "..KwKGGWGGGGGK..",
    "..KwKGGGGGGGGK..",
    "..KwKGGGGGgGK...",
    "..KwKGGGGGGK....",
    "..KwKKKKKKK.....",
    "..KwK...........",
    "..KwK...........",
    "..KwK...........",
    "..KwK...........",
    ".KKwKK..........",
    "KwwwwwK.........",
    "KKKKKKK.........",
  ]),
  // a trophy
  score: icon([
    "................",
    "...KKKKKKKKKK...",
    ".KKKYWYYYYYyKKK.",
    "KY.KYWYYYYYyK.YK",
    "KY.KYWYYYYYyK.YK",
    ".KYKYYYYYYYyKYK.",
    "..KKYYYYYYYyKK..",
    "....KYYYYYyK....",
    ".....KYYYyK.....",
    "......KYyK......",
    "......KYyK......",
    ".....KKYyKK.....",
    "....KyyyyyyK....",
    "...KKKKKKKKKK...",
    "...KddddddddK...",
    "...KKKKKKKKKK...",
  ]),
  // a fish
  fish: icon([
    "................",
    "................",
    "................",
    ".....KKKKK....KK",
    "...KKBBBBBKK.KBK",
    "..KBBBBBBBBBKBBK",
    ".KBWKBBBbBBBBBBK",
    ".KBKKBBbBBBBBBK.",
    ".KBBBBBbBBBBBBK.",
    ".KBBBBBBbBBBBBBK",
    "..KbbbbbbbbbKbbK",
    "...KKbbbbbKK.KbK",
    ".....KKKKK....KK",
    "................",
    "................",
    "................",
  ]),
  // a pigeon
  pigeons: icon([
    "................",
    "................",
    "....KKK.........",
    "...KwwwK........",
    "..KwKwwwK.......",
    "KKAwwwwwK.......",
    "..KKwwwwwKKKK...",
    "....KwwwwwwwwKK.",
    "....KwCwwwwwwwwK",
    "....KwCCwwwwwwK.",
    ".....KwwwwwwwK..",
    "......KKKKKKK...",
    ".......K..K.....",
    "......KK.KK.....",
    "................",
    "................",
  ]),
  // a crescent moon and stars
  night: icon([
    "................",
    "......KKKK...Y..",
    "....KKYYYK..YYY.",
    "...KYYYK.....Y..",
    "..KYYYK.........",
    "..KYYK......Y...",
    ".KYYYK..........",
    ".KYYYK..........",
    ".KYYYK.......KK.",
    ".KYYYYK....KKYK.",
    "..KYYYYKKKKYYK..",
    "..KYYYYYYYYYyK..",
    "...KYYYYYYYyK...",
    "....KKyyyyKK....",
    "......KKKK......",
    "................",
  ]),
  // two beamed notes
  dj: icon([
    "................",
    ".....KKKKKKKKKKK",
    ".....KGGGGGGGGGK",
    ".....KGKKKKKKKGK",
    ".....KGK.....KGK",
    ".....KGK.....KGK",
    ".....KGK.....KGK",
    ".....KGK.....KGK",
    ".....KGK.....KGK",
    "..KKKKGK..KKKKGK",
    ".KGGGGGK.KGGGGGK",
    ".KGGGGGK.KGGGGGK",
    "..KGGGK...KGGGK.",
    "...KKK.....KKK..",
    "................",
    "................",
  ]),
  // a game pad
  konami: icon([
    "................",
    "................",
    "................",
    "................",
    "KKKKKKKKKKKKKKKK",
    "KwwwwwwwwwwwwwwK",
    "KwwKKwwwwwwwwwwK",
    "KwKKKKwddwwwwwwK",
    "KwKKKKwwwwRwwRwK",
    "KwwKKwwddwwwwwwK",
    "KwwwwwwwwwwwwwwK",
    "KKKKKKKKKKKKKKKK",
    "................",
    "................",
    "................",
    "................",
  ]),
};

export function iconSvg(id: string, size = 48) {
  const i = ICONS[id];
  if (!i) return "";
  const w = i.sprite[0].length;
  const h = i.sprite.length;
  const rects: string[] = [];
  i.sprite.forEach((row, y) =>
    [...row].forEach((ch, x) => {
      if (ch !== ".") rects.push(`<rect x="${x}" y="${y}" width="1" height="1" fill="${i.palette[ch]}"/>`);
    }),
  );
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${size}" height="${size}" shape-rendering="crispEdges" aria-hidden="true">${rects.join("")}</svg>`;
}
